"""Add points column to Task model

Revision ID: cc334eb97b97
Revises: ed1c89703f66
Create Date: 2025-10-30 21:36:21.458666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc334eb97b97'
down_revision = 'ed1c89703f66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task', sa.String(length=200), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('planners')
    with op.batch_alter_table('nudges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('impact_score', sa.Integer(), nullable=True))
        batch_op.drop_column('description')

    with op.batch_alter_table('rewards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rewards', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('nudges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('impact_score')
        batch_op.drop_column('category')
        batch_op.drop_column('message')

    op.create_table('planners',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('goal', sa.VARCHAR(length=100), nullable=True),
    sa.Column('completed', sa.BOOLEAN(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('tasks')
    # ### end Alembic commands ###
